select 20+4 'Toplam', 20-4 as 'Fark', 20*4 as 'Çarpým', 20/4 as 'Bölüm'

select * from TBLNOTLAR where DERS=1

update TBLNOTLAR set SINAV2=SINAV2+10 FROM TBLNOTLAR WHERE DERS=1

SELECT * FROM TBLNOTLAR 

update TBLNOTLAR set SINAV2=100 where SINAV2>100

SELECT avg(ORTALAMA) from TBLNOTLAR where DERS=1

select abs(-65) as 'Mutlak'
select POWER (2,4) as 'Üs Alma'
select POWER(SINAV1,2) from TBLNOTLAR
select SQRT (81) as 'Karakök'
select FLOOR (4.56) as 'Taban' , CEILING(4.56) 'Tavan'


select SUM(SINAV1) FROM TBLNOTLAR WHERE OGRENCÝ=1
SELECT SINAV1,DERS FROM TBLNOTLAR WHERE OGRENCÝ=1

SELECT DERSAD,SINAV1 FROM TBLNOTLAR 
INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS=TBLDERSLER.DERSID WHERE OGRENCÝ=1