update TBLOGRENCÝLER  set OGRKULUP =4 where OGRKULUP='Gezi'

insert into TBLOGRENCÝLER (OGRAD,OGRKULUP,OGRSEHÝR) values ('Þehmus',4,'Batman')

select NOTID,DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM from TBLNOTLAR INNER JOIN TBLDERSLER on TBLNOTLAR.DERS=TBLDERSLER.DERSID

select NOTID,OGRAD,DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM 
from TBLNOTLAR
INNER JOIN TBLDERSLER on TBLNOTLAR.DERS=TBLDERSLER.DERSID
INNER JOIN TBLOGRENCÝLER ON TBLOGRENCÝLER.OGRID=TBLNOTLAR.OGRENCÝ


select NOTID,OGRAD +' '+OGRSOYAD as 'ad soyad' ,DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM 
from TBLNOTLAR
INNER JOIN TBLDERSLER on TBLNOTLAR.DERS=TBLDERSLER.DERSID
INNER JOIN TBLOGRENCÝLER ON TBLOGRENCÝLER.OGRID=TBLNOTLAR.OGRENCÝ

select * from TBLNOTLAR 

update TBLNOTLAR set ORTALAMA=(SINAV1+SINAV2+SINAV3)/3 where DERS=1

update TBLNOTLAR set DURUM=1 where ORTALAMA>=50

update TBLNOTLAR set DURUM=0 where ORTALAMA<=50
--dersler tablosundaki ismi matamatik olan derse ait sýnav not bilgisi 
-- sub Query (Alt sorgu) // sondan baþa doðru düþünmeyye çalýþ buralarda
select * from TBLNOTLAR where DERS=(select DERSID from TBLDERSLER where DERSAD='Matamatik')

select * from TBLNOTLAR 
left JOIN TBLOGRENCÝLER
ON TBLNOTLAR.OGRENCÝ=TBLOGRENCÝLER.OGRID

select * from TBLNOTLAR 
Right JOIN TBLOGRENCÝLER
ON TBLNOTLAR.OGRENCÝ=TBLOGRENCÝLER.OGRID

select * from TBLNOTLAR 
Full JOIN TBLOGRENCÝLER
ON TBLNOTLAR.OGRENCÝ=TBLOGRENCÝLER.OGRID